Reordering of AMD readings, Java benchmark with Panama, README changes
cs-23-pt-9-01/rapl-rust-test pull request #22
Opened 2023-10-11 07:12 UTC by Jakobzs

2023-10-11 07:35 UTC, sabj17 reviewed
More comments plz

2023-10-11 08:03 UTC, Mads518d commented on rapl-bin/src/main.rs
>  pub fn bench_test(n: i32) -> i32 {
hvad er "i32"?

2023-10-11 08:06 UTC, Mads518d approved these changes
Jeg ved ikke nok om RAPL til at kunne sige om det vi gør er rigtigt eller forkert så jeg stoler på jer

2023-10-11 08:13 UTC, Villiamfj requested changes

2023-10-11 08:13 UTC, Villiamfj commented on benchmarks/fibjava/Bench.java
> +        System.out.println(result);
De andre benches printer ikke deres resultat.

2023-10-11 08:13 UTC, Villiamfj commented on benchmarks/fibjava/Bench.java
> +
where da loop at?

2023-10-11 08:18 UTC, Jakobzs commented on benchmarks/fibjava/Bench.java
> +        System.out.println(result);
wow

2023-10-11 08:18 UTC, Jakobzs commented on benchmarks/fibjava/Bench.java
> +
wow

2023-10-13 06:45 UTC, sabj17 commented on benchmarks/FibSequence/fibjava/Bench.java
We should consider writing some documentation for this - comments etc. (at least as a header for the file)

2023-10-13 06:46 UTC, Villiamfj approved these changes

2023-10-13 06:47 UTC, sabj17 reviewed
We should consider better documentation for our code. At least a short explanation in the beginning of each (important) file.

2023-10-13 07:03 UTC, Villiamfj commented on benchmarks/FibSequence/fibjava/Bench.java
Added some comments to the file

2023-10-13 07:09 UTC, merged