Quicksort
cs-23-pt-9-01/rapl-rust-test pull request #38
Opened 2023-10-30 12:57 UTC by Villiamfj

2023-10-30 13:19 UTC, Mads518d commented on benchmarks/quicksort/c/bench.c
Der bliver brugt en del ref til merge hvilket nok ikke er helt korrekt

2023-10-30 13:20 UTC, Jakobzs requested changes

2023-10-30 13:20 UTC, Jakobzs commented on benchRunners/quicksort.sh
> +count=1000
Count skal være under testname "folder" reeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

2023-10-30 13:30 UTC, Mads518d commented on benchmarks/quicksort/cpp/bench.cpp
Der bliver også her ref'et til merge

2023-10-30 13:41 UTC, Mads518d commented on benchmarks/quicksort/java/Bench.java
> +        // by the compiler due to the fact that the result is not used.
```suggestion
```

2023-10-30 13:41 UTC, Mads518d commented on benchmarks/quicksort/java/Bench.java
> +        // Note that this could potentially be optimized away
```suggestion
```

2023-10-30 13:47 UTC, Mads518d commented on benchmarks/quicksort/python/bench.py
> +from heapq import merge
ikke brugt

2023-10-31 08:05 UTC, Villiamfj commented on benchRunners/quicksort.sh
> +count=1000
![IAmDoneGIF](https://github.com/cs-23-pt-9-01/rapl-interface/assets/40019337/8926d945-62e2-430d-a11a-ec3dbd33eb32)

2023-10-31 08:06 UTC, Jakobzs requested changes

2023-10-31 08:06 UTC, Jakobzs commented on benchmarks/quicksort/c/bench.c
![SwagGIF](https://i.gifer.com/origin/8e/8eddee8c03501d02843f886b26247663_w200.gif)

2023-10-31 08:06 UTC, Jakobzs commented on benchRunners/quicksort.sh
> +Input=`cat benchRunners/mergeSortParam` # getting input from file
```suggestion
input=`cat benchRunners/mergeSortParam` # getting input from file
```

2023-10-31 08:06 UTC, Jakobzs commented on benchRunners/quicksort.sh
> +Input=`cat benchRunners/mergeSortParam` # getting input from file
Lille i reeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

2023-10-31 08:07 UTC, Mads518d commented on benchRunners/quicksort.sh
> +Input=`cat benchRunners/mergeSortParam` # getting input from file
🤓

2023-10-31 08:08 UTC, Mads518d commented on benchRunners/quicksort.sh
> +Input=`cat benchRunners/mergeSortParam` # getting input from file
ಠ_ಠ

2023-10-31 08:09 UTC, Villiamfj commented on benchRunners/quicksort.sh
> +Input=`cat benchRunners/mergeSortParam` # getting input from file
Lavede en ctrl f

2023-10-31 09:01 UTC, Mads518d commented on benchmarks/mergesort/javascript/bench.js
> +    let toBeSorted = Array.from(mergeParam);
Du kan meget godt lide denne "mergeParam"

2023-10-31 09:25 UTC, Mads518d approved these changes
if it works it works

2023-10-31 09:36 UTC, Jakobzs approved these changes

2023-10-31 11:53 UTC, merged