raspberry prints into a file
cs-23-pt-9-01/rapl-rust-test pull request #43
Opened 2023-11-03 08:34 UTC by Villiamfj

the prints are now stored in a file called "log.out".

2023-11-03 09:20 UTC, Jakobzs requested changes

2023-11-03 09:20 UTC, Jakobzs commented on utils/raspberry_logger.sh
> +ssh  -i $HOME/.ssh/id_rsa $HOSTNAME@$IP $COMMAND &
```suggestion
ssh -i $HOME/.ssh/id_rsa $HOSTNAME@$IP $COMMAND &
```

2023-11-03 10:25 UTC, Jakobzs approved these changes

2023-11-06 08:06 UTC, Mads518d approved these changes

2023-11-06 12:38 UTC, merged